### ISSUE TITLE
Abstract code to remove specific site references

### ISSUE THREAD

**Issue by bens2018** [cmpunches/Machapi#9]
Since the project is now a modular engine for demonstrating site automation, please remove all references targeting specific commercial websites.

**Comment by cmpunches** [comment]
Hey Ben.  Welcome to github, and thanks for following the proper process to request changes.  You're going to find the interactive nature of the issue tracker to be favorable after a brief period of orientation.

# Context
For the benefit of the readers, full transparency in disclosure is necessary.

 - I've been in talks with Match Group's counsel regarding various concerns they have about the Machapi library that have guided its development track and feature catalog recently.
 -   These talks finally reached a point where they were told to use the issue tracker like everybody else.  Ben is the attorney representing Match Group.  **My agreement to this was contingent on all access authorization being restored**.
 -  I am glad to see an amicable process established and intend to be cooperative without compromising the value of the product.
 
 # Barriers

 - I'll want to analyse and test a few alternatives/options while a discussion on options takes place.   
 - A document serving as a reversal of the notice sent on 2018-07-03 (titled "*Revocation of Authorization and Demand to Cease and Desist*") has not yet arrived in my inbox yet; I am sure it just hasn't had enough time to be drafted, so, I will wait for that to come in before discussing options in depth on this request or implementing or testing any changes regarding it.

# Once Cleared

The engine itself is going to be agnostic of what site it connects to but the modules that the engine uses will not be by design.  That is the function of the engine and those are the functions of the modules.

Are we discussing moving the modules to their own repo or are we discussing moving all module-specific references to the modules?

**Comment by cmpunches** [comment]
@bens2018 -- for clarification, this issue is pending items from you and requires action on your part to be worked.  I will hold this issue open until 2018-07-13 to give you some time to do what's needed of you.

**Comment by cmpunches** [comment]
@bens2018 -- based on your "out of band" communication last night it's apparent you did not understand what's needed from you for this issue to be worked or discussable, so, I'm holding this ticket open until about midnight tonight to give you some time to wrap it up.

**Comment by cmpunches** [comment]
This issue is not able to be worked due to either the user's failure or refusal to provide additional required information or statements with plenty of time to do so. 

I am closing this issue.

For transparency, based on previous interactions I suspect this is more of the same types of behaviours designed to pretext a narrative for further victim-posturing attempts, and my position remains the same:  

_Being polite in the wording of your communications does not obfuscate the fact that you have taken a **hostile** position._ 

This is not inspiring me to the cooperation you desire and I am not obligated to provide it -- this process exists as a courtesy to allow you to see the types of changes you would like and you have obstructed it with inaction.
